### ISSUE TITLE
Istio gateway is not redirecting to k8s service

### ISSUE THREAD

**Issue by arun-gupta** [arun-gupta/java-k8s#13]
Istio ingress gateway is not directing the call to k8s service:

Application manifest at https://github.com/arun-gupta/java-k8s/blob/master/manifests/app-ingress.yaml, inlined below:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: arungupta/greeting
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: greeting
spec:
  selector:
    app: greeting
  ports:
  - name: http
    protocol: TCP
    port: 80
```

Gateway & Virtual service at https://github.com/arun-gupta/java-k8s/blob/master/manifests/greeting-delay.yaml and inlined below:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: greeting
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: greeting
spec:
  hosts:
  - greeting
  gateway:
  - greeting
  http:
  - match:
    - uri:
      prefix: "/"
  # - fault:
  #     delay:
  #       percent: 100
  #       fixedDelay: 5s
    route:
    - destination:
        host: greeting
        port:
          number: 8080
```

Accessing the service as curl http://$INGRESS_HOST:$INGRESS_PORT/resources/greeting shows the following in the gateway logs:

```
[2018-07-06T19:30:38.805Z] "GET /resources/greeting HTTP/1.1" 404 - 0 0 1 - "172.20.87.230" "curl/7.54.0" "737383a8-17c9-9807-ba66-7cc73390b405" "a741709027f1911e8b92c06420d9644d-2103574560.us-west-2.elb.amazonaws.com" "-"
```

Seems like the Ingress port 80 is not redirecting to the service port 8080. What is missing?

**Comment by ZackButcher** [comment]
You need to set the host header to `"greeting"`, the host in your VirtualService, when you curl the gateway. This should work: `curl http://$INGRESS_HOST:$INGRESS_PORT/resources/greeting -H "Host: greeting"`

**Comment by arun-gupta** [comment]
Still the same error:

```
[libprotobuf INFO src/istio/mixerclient/check_cache.cc:155] Add a new Referenced for check cache: Absence-keys: adapter_template_kubernetes.output.source_service, adapter_template_kubernetes.output.source_service_account_name, source.uid, Exact-keys: context.protocol, destination.service, destination.uid, source.ip, 
[2018-07-10T21:15:49.057Z] "GET /resources/greeting HTTP/1.1" 404 - 0 0 2 - "172.20.102.211" "curl/7.54.0" "ed9eac19-9fa7-93e8-8a97-c7de0f9857d3" "greeting" "-"
```

Do the Service, VirtualService, Deployment and Gateway ports look correct?

Accessing the pod directly using `kubectl exec` seems to work:

```
$ kubectl get pods
NAME                       READY     STATUS    RESTARTS   AGE
greeting-9c76fc57f-dhzn8   1/1       Running   0          1m
$ kubectl exec -it greeting-9c76fc57f-dhzn8 bash
root@greeting-9c76fc57f-dhzn8:/opt/target# curl http://localhost:8080/resources/greeting
Helloroot@greeting-9c76fc57f-dhzn8:/opt/target# exit
exit
```

**Comment by arun-gupta** [comment]
Here are the current port settings:

- `containerPort` in `Deployment` = `8080`
- `port` in `Service` = `8080` 
- `route.destination.port.number` in `VirtualService` = 8080
- `port` in `Gateway` = 80

Here is the log:

```
[2018-07-10 21:42:02.265][42][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:442] removing cluster outbound|8080||greeting.default.svc.cluster.local
[2018-07-10 21:42:12.584][42][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:390] add/update cluster outbound|8080||greeting.default.svc.cluster.local starting warming
[2018-07-10 21:42:12.584][42][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:397] warming cluster outbound|8080||greeting.default.svc.cluster.local complete
[2018-07-10 21:42:23.153][42][info][upstream] external/envoy/source/server/lds_api.cc:62] lds: add/update listener '0.0.0.0_80'
[libprotobuf INFO src/istio/mixerclient/check_cache.cc:155] Add a new Referenced for check cache: Absence-keys: adapter_template_kubernetes.output.source_service, adapter_template_kubernetes.output.source_service_account_name, source.uid, Exact-keys: context.protocol, destination.service, destination.uid, source.ip, 
[2018-07-10T21:42:36.226Z] "GET /resources/greeting HTTP/1.1" 404 - 0 0 2 - "172.20.88.227" "curl/7.54.0" "2e1dd02e-a9b5-945d-badf-82810e5ce740" "greeting" "-"
```

Same error. This is a basic usecase and something seems definitely amiss on my side.

**Comment by ZackButcher** [comment]
Sorry, I'm not close to a cluster to test before giving advice. Reading over I _think_ you need your k8s service to set the targetPort to 8080:

<pre>
apiVersion: v1
kind: Service
metadata:
  name: greeting
spec:
  selector:
    app: greeting
  ports:
  - name: http
    protocol: TCP
    port: 80
    <b>targetPort: 8080</b>
</pre>

IIRC the way we process k8s `Service` resources, your config means Istio creates a listener on port 80 for HTTP traffic, but it hits the pod on port 8080.

The other thing to check is that all of this config is in the same namespace? Otherwise you'd need to use FQDN:

<pre>
apiVersion: v1
kind: Service
metadata:
  name: greeting
  <b>namespace: default</b>
spec:
  selector:
    app: greeting
  ports:
  - name: http
    protocol: TCP
    port: 80
    <b>targetPort: 8080</b>
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  <b>name: greeting-gateway</b>
  <b>namespace: default</b>
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: greeting
  <b>namespace: default</b>
spec:
  hosts:
  - <b>greeting-gateway.default.svc.cluster.local</b>
  gateway:
  - greeting
  http:
  - match:
    - uri:
      prefix: "/"
    route:
    - destination:
        host: <b>greeting.default.svc.cluster.local</b>
        port:
          number: 8080
</pre>

**Comment by arun-gupta** [comment]
All of them are in the `default` namespace.

Here are the updated config files:

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: greeting
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: greeting
spec:
  hosts:
  - greeting
  gateways:
  - greeting
  http:
  - match:
    - uri:
      prefix: "/"
  # - fault:
  #     delay:
  #       percent: 100
  #       fixedDelay: 5s
    route:
    - destination:
        host: greeting
        port:
          number: 8080
```

and


```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: arungupta/greeting
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: greeting
spec:
  selector:
    app: greeting
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
```

Still same result:

```
[2018-07-10T22:14:31.462Z] "GET /resources/greeting HTTP/1.1" 404 - 0 0 2 - "100.96.3.1" "curl/7.54.0" "a9741e45-3a03-922e-bc86-12cf322579df" "greeting" "-"
```
